name: CobbleConverter
main: com.trentsterling.cobbleconverter.CobbleConverterPlugin
authors: [Xryan, Nacho]
version: 0.0.1
commands:
   convert:
      description: This will convert your cobble into shop tokens
      usage: /<command> [amount]
   unconvert:
      description: This will convert your cobble into shop tokens
      usage: /<command> [amount]